---
# Ubuntu related OS tasks

- name: apt dist-upgrade
  apt:
    upgrade: dist
    autoremove: true
  when: apt_dist_upgrade

- name: install additional packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - zip
    - unzip
    - bzip2
    - screen
    - curl
    - ffmpeg
    - imagemagick 
    - libfile-fcntllock-perl
    - language-pack-en-base
    - software-properties-common
    - facter
